src/CodingCode.Web/ViewModels/DalInfoViewModel.cs
namespace CodingCode.Web.ViewModels
{
    public class DalInfoViewModel
    {
        public string Server { get; set; }
        public string Database { get; set; }
    }
}

src/CodingCode.Web/ViewModels/DatabaseCodedViewModel.cs
namespace CodingCode.Web.ViewModels
{
    public class DatabaseCodedViewModel
    {
        public string AssemblyName { get; set; }
    }
}

src/CodingCode.Web/ViewModels/TableViewModel.cs
namespace CodingCode.Web.ViewModels
{
    public class TableViewModel
    {
        public string[] ColumnNames { get; set; }

        public string TableName { get; set; }

        public string[,] Values { get; set; }
    }
}

src/CodingCode.Web/Controllers/DataAccessScaffoldController.cs
namespace CodingCode.Web.Controllers
{
    using System.Threading.Tasks;
    using CodingCode.Abstraction;
    using CodingCode.Services;
    using CodingCode.ViewModel;
    using Microsoft.AspNet.Mvc;

    public class DataAccessScaffoldController : Controller
    {
        [HttpGet]
        public IActionResult CodeDatabase() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CodeDatabase(DataAccessViewModel dataAccessViewModel,
            [FromServices] DatabaseContextWrapper dbContextWrapper, [FromServices] IContextGenerator contextGenerator)
        {
            if (!ModelState.IsValid) return View(dataAccessViewModel);

            string assemblyName = ComposeAssemblyName(dataAccessViewModel);
            
            if (!dbContextWrapper.Exists(assemblyName))
                dbContextWrapper[assemblyName] = await contextGenerator.GenerateAsync(dataAccessViewModel, assemblyName);
                
            return RedirectToAction(nameof(DynamicRaportController.Index), "DynamicRaport", new { assemblyName = assemblyName });
        }
        
        private static string ComposeAssemblyName(DataAccessViewModel dataAccessViewModel){
          return string.Concat(dataAccessViewModel.ServerName.Replace("\\", "_"), dataAccessViewModel.DatabaseName);
        }
    }
}

src/CodingCode.Web/Controllers/DynamicRaportController.cs
namespace CodingCode.Web.Controllers
{
    using System;
    using CodingCode.Abstraction;
    using Common.Core;
    using Microsoft.AspNet.Mvc;
    using Services;

    public class DynamicRaportController : Controller
    {
        [HttpGet]
        public IActionResult Index(string assemblyName)
        {
            try
            {
                ViewData[nameof(assemblyName)] = Check.NotNullOrWhiteSpace(assemblyName, nameof(assemblyName));
            }
            catch (Exception)
            {
                return View(nameof(HomeController.Error));
            }
            return View();
        }

        [HttpGet]
        public IActionResult RandomTable(string assemblyName,
                [FromServices] IRandomTablePicker randomTablePicker,
                [FromServices] ITableDataProviderFactory tableDataProviderFactoy,
                [FromServices] DatabaseContextWrapper dbContextWrapper)
        {
            var randomType = randomTablePicker.GetRandomTable(dbContextWrapper[assemblyName]);
            var maxNumberOfRows=50;
            var tableProvider = tableDataProviderFactoy.Create(dbContextWrapper[assemblyName], randomType, maxNumberOfRows);
            return View(tableProvider.MapToViewModel());
        }
    }
}

src/CodingCode.Web/Controllers/HomeController.cs
namespace CodingCode.Web.Controllers
{
    using Microsoft.AspNet.Mvc;

    public class HomeController : Controller
    {
        public IActionResult Error() => View("~/Views/Shared/Error.cshtml");
    }
}

src/CodingCode.Web/ViewComponents/CssLinksViewComponent.cs
namespace CodingCode.Web.ViewComponents
{
    using Microsoft.AspNet.Hosting;
    using Microsoft.AspNet.Mvc;
    public class CssLinksViewComponent : ViewComponent
    {
        private bool _isDevelopment;
        public CssLinksViewComponent(IHostingEnvironment hostingEnv)
        {
            _isDevelopment = hostingEnv.IsDevelopment();
        }

        public IViewComponentResult Invoke()
        {
            if (_isDevelopment) return View("Development");
            return View();
        }
    }
}

src/CodingCode.Web/ViewComponents/JavascriptLinksViewComponent.cs
namespace CodingCode.Web.ViewComponents
{
    using Microsoft.AspNet.Hosting;
    using Microsoft.AspNet.Mvc;
    public class JavascriptLinksViewComponent : ViewComponent
    {
        private bool _isDevelopment;
        public JavascriptLinksViewComponent(IHostingEnvironment hostingEnv)
        {
            _isDevelopment = hostingEnv.IsDevelopment();
        }
        
        public IViewComponentResult Invoke()
        {
            if (_isDevelopment) return View("Development");
            return View();
        }
    }
}

src/CodingCode.Web/Views/DataAccessScaffold/CodeDatabase.cshtml
@using CodingCode.ViewModel
@model DataAccessViewModel
<form asp-controller="DataAccessScaffold" asp-action="CodeDatabase" method="post" class="form-horizontal" role="form">
    <hr />
    <div class="form-group">
        <label asp-for="ServerName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ServerName" class="form-control" placeholder="enter server name"
                   type="text" value="DELL\SQLEXPRESS" />
            <span asp-validation-for="ServerName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="DatabaseName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="DatabaseName" class="form-control" placeholder="enter server name"
                   type="text" value="Northwind" />
            <span asp-validation-for="DatabaseName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default pull-right">Connect</button>
    </div>
</form>

@section Scripts {
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">
        $(document).ready(disableSubmit);
    </script>
}

src/CodingCode.Web/Views/DynamicRaport/Index.cshtml
@using System.Threading.Tasks
@using CodingCode.ViewModel

<h2>Database Model succesfully created!</h2>
<a asp-controller="DynamicRaport" asp-action="RandomTable" asp-route-assemblyName="@ViewData["assemblyName"]">Look into random table!</a>

src/CodingCode.Web/Views/DynamicRaport/RandomTable.cshtml
@using CodingCode.ViewModel
@model TableViewModel
<h3>@Model.TableName</h3>
<table class="table">
    <thead>
        <tr>
            @foreach (var columnName in Model.ColumnNames)
            {
                <th>@columnName</th>
            }
        </tr>
    </thead>
    @{ var tmp = Model.Values;}
    @for (int i = 0; i <= tmp.GetUpperBound(0); i++)
    {
        <tr>
            @for (int j = 0; j <= tmp.GetUpperBound(1); j++)
            {
                <td>@tmp[i, j]</td>
            }
        </tr>
    }
</table>

src/CodingCode.Web/Views/Shared/Components/CssLinks/Default.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
<link rel="stylesheet" href="~/css/site.css" />

src/CodingCode.Web/Views/Shared/Components/CssLinks/Development.cshtml
<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
        asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
        asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/css/bootstrap-touch-carousel.css"
        asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css"
        asp-fallback-test-class="carousel-caption" asp-fallback-test-property="display" asp-fallback-test-value="none" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

src/CodingCode.Web/Views/Shared/Components/JavascriptLinks/Default.cshtml
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
</script>
<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
</script>
<script src="https://ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
        asp-fallback-src="~/lib/hammer.js/hammer.js"
        asp-fallback-test="window.Hammer">
</script>
<script src="https://ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/js/bootstrap-touch-carousel.js"
        asp-fallback-src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"
        asp-fallback-test="window.Hammer && window.Hammer.Instance">
</script>
<script src="~/js/site.js" asp-append-version="true"></script>

src/CodingCode.Web/Views/Shared/Components/JavascriptLinks/Development.cshtml
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="~/lib/hammer.js/hammer.js"></script>
<script src="~/lib/knockout/dist/knockout.js"></script>
<script src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"></script>

src/CodingCode.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - CodingCode</title>
        @Component.Invoke("CssLinks")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="DataAccessScaffold" asp-action="CodeDatabase" class="navbar-brand">Coding Code</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="DataAccessScaffold" asp-action="CodeDatabase">Home</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2016 - CodingCode</p>
            </footer>
        </div>
        @Component.Invoke("JavascriptLinks")
        @RenderSection("scripts", required: false)
    </body>
</html>